name: {{ .Values.spec_name }}

static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: {{ .Values.deploy_on_push }}
    repo: renehernandez/sample-html
  name: hello
  instance_size_slug: hello-word

region: {{ .Values.region }}