# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats: []

