site_name: appfile
site_author: Rene Hernandez

repo_name: renehernandez/appfile
repo_url: https://github.com/renehernandez/appfile/
edit_uri: ''

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - CLI Reference: cli_reference.md
    - Writing appfile: writing_appfile.md
    - Examples: examples.md
  - About:
    - Changelog: CHANGELOG.md
    - License: LICENSE.md
    - Contributing: Contributing.md

theme:
  name: material
  features:
    - navigation.tabs
  collapse_navigation: false
  hljs_languages:
    - yaml
    - dockerfile

markdown_extensions:
  # meta, toc, table and fenced_code extensions are included by default
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true