name: {{ .Values.spec_name }}

services:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: {{ .Values.deploy_on_push }}
    repo: renehernandez/sample-html
  name: sample-html-{{ .Environment.Name }}
region: {{ .Values.region }}