name: CI

on:
  push:
    tags-ignore:
      - v*
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - name: check
        run: |
          make check
      - name: fmt
        run: make fmt
      - name: pristine
        run: |
          make pristine

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - name: test
        run: make test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - name: build
        run: make build