name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - '.github/workflows/release*.yml'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: check
        run: |
          make check
      - name: fmt
        run: make fmt
      - name: pristine
        run: |
          make pristine

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: test
        run: make test

  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Create releases
        run: |
          make tools
          make release

  build_docs:
    name: Build Pre Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python3 -m pip install -r ./docs/scripts/requirements.txt
      - name: Build site
        env:
          APPFILE_VERSION: ${{ env.CI_REF_NAME }}
        run: |
          go run ./docs/scripts/docs.go
          ./docs/scripts/copy_docs.sh
          mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        if: env.CI_REF_NAME == 'main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: dev
          publish_dir: ./site