name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
    paths-ignore:
      - '.github/workflows/release*.yml'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - name: check
        run: |
          make check
      - name: fmt
        run: make fmt
      - name: pristine
        run: |
          make pristine

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - name: test
        run: make test

  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Create releases
        run: |
          make tools
          make release