name: Release Brew

on:
  release:
    types: [created, published]

jobs:
  formula:
    name: Update Homebrew formula
    needs: [release_notes]
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: renehernandez/homebrew-taps
          formula: Formula/appfile.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}

  bottle_macos_catalina:
    name: Build and distribute Homebrew bottle for macOS Catalina
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew tap renehernandez/taps
          brew install --build-bottle --verbose appfile
          brew bottle appfile
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./appfile--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_name: appfile-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip
      - name: Update the Homebrew formula again with bottle
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: renehernandez/homebrew-taps
          formula: Formula/appfile.rb
          message: |
              Add bottle for appfile ${{ github.event.release.tag_name }}
              on macOS Catalina
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}

  bottle_macos_big_sur:
    name: Build and distribute Homebrew bottle for macOS Big Sur
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew tap renehernandez/taps
          brew install --build-bottle --verbose appfile
          brew bottle appfile
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./appfile--${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_name: appfile-${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_content_type: application/gzip
      - name: Update the Homebrew formula again with bottle
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: renehernandez/homebrew-taps
          formula: Formula/appfile.rb
          message: |
              Add bottle for appfile ${{ github.event.release.tag_name }}
              on macOS Big Sur
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}