name: Release

on:
  push:
    tags:
      - v*

jobs:
  artifacts:
    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Create releases
        run: |
          make tools
          make release
      - name: Cache release binaries
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.GITHUB_REF_NAME_SLUG }}

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    needs: [artifacts]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag ${{ env.GITHUB_REF_NAME }}
          file_pattern: CHANGELOG.md

  release_notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.GITHUB_REF_NAME }}
          path: CHANGELOG.md

      - name: Load release binaries
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.GITHUB_REF_NAME_SLUG }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          name: ${{ env.GITHUB_REF_NAME }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
          files: |
            dist/*

  formula:
    name: Update Homebrew formula
    needs: [release_notes]
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: rene/homebrew-taps
          formula: Formula/appfile.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}

  bottle_macos_catalina:
    name: Build and distribute Homebrew bottle for macOS Catalina
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew tap renehernandez/taps
          brew install --build-bottle --verbose appfile
          brew bottle appfile
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./appfile--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_name: appfile-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip
      - name: Update the Homebrew formula again with bottle
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: renehernandez/homebrew-taps
          formula: Formula/appfile.rb
          message: |
              Add bottle for appfile ${{ github.event.release.tag_name }}
              on macOS Catalina
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}

  bottle_macos_big_sur:
    name: Build and distribute Homebrew bottle for macOS Big Sur
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew tap renehernandez/taps
          brew install --build-bottle --verbose appfile
          brew bottle appfile
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./appfile--${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_name: appfile-${{ github.event.release.tag_name }}.big_sur.bottle.tar.gz
          asset_content_type: application/gzip
      - name: Update the Homebrew formula again with bottle
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: renehernandez/appfile
          tap: renehernandez/homebrew-taps
          formula: Formula/appfile.rb
          message: |
              Add bottle for appfile ${{ github.event.release.tag_name }}
              on macOS Big Sur
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.APPFILE_BREW_TOKEN }}