name: Release

on:
  push:
    tags:
      - v*

jobs:
  artifacts:
    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Create releases
        run: |
          make tools
          make release
      - name: Cache release binaries
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.GITHUB_REF_NAME_SLUG }}

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    needs: [artifacts]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag ${{ env.GITHUB_REF_NAME }}
          file_pattern: CHANGELOG.md

  deploy_docs:
    name: Build Release Docs
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python3 -m pip install -r ./docs/scripts/requirements.txt
      - name: Build site
        env:
          APPFILE_VERSION: ${{ env.CI_REF_NAME }}
        run: |
          go run ./docs/scripts/docs.go
          ./docs/scripts/copy_docs.sh
          mkdocs build
      - name: Push site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ${{ env.CI_REF_NAME }}
          publish_dir: ./site
      - name: Push redirect
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/redirect
          keep_files: trues

  release_notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.GITHUB_REF_NAME }}
          path: CHANGELOG.md

      - name: Load release binaries
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.GITHUB_REF_NAME_SLUG }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          # Needs to use PAT in order to triggerng downstream workflow to update brew formula
          GITHUB_TOKEN: ${{ secrets.CREATE_APPFILE_RELEASE_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          name: ${{ env.GITHUB_REF_NAME }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
          files: |
            dist/*
